export const s = {
  page: {
    minHeight: "100vh",
    background: "#111",
    color: "#fff",
    padding: 24,
    fontFamily: "sans-serif",
    maxWidth: 560,
    margin: "0 auto",
    width: "100%",
    boxSizing: "border-box",
  },
  kicker: { color: "#ff8a00", fontWeight: 900, margin: 0 },
  title: { fontSize: 42, margin: "8px 0" },
  sub: { color: "#aaa", fontWeight: 700, margin: "0 0 8px" },
  muted: { color: "#aaa", margin: 0 },
  hint: { color: "#888", margin: 0, fontSize: 14, fontWeight: 700 },
  card: { background: "#ff6a00", borderRadius: 24, padding: 24, margin: "16px 0" },
  cardLabel: { margin: 0, fontWeight: 900 },
  cardValue: { margin: "8px 0 0", fontSize: 36, fontWeight: 900 },
  cardSub: { margin: "8px 0 0", color: "#fff7ed", fontWeight: 700 },
  dashGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(140px, 1fr))",
    gap: 10,
    marginBottom: 8,
  },
  miniCard: { background: "#1f1f1f", border: "1px solid #333", borderRadius: 20, padding: 18, marginBottom: 0 },
  miniCount: { margin: "8px 0 0", fontSize: 22, fontWeight: 900, lineHeight: 1.3, wordBreak: "break-all" },
  menuGroup: { marginTop: 8 },
  menuLabel: { color: "#888", fontSize: 13, fontWeight: 900, margin: "12px 0 4px 4px" },
  btn: {
    width: "100%",
    padding: 18,
    marginTop: 8,
    borderRadius: 18,
    border: "1px solid #333",
    background: "#1f1f1f",
    color: "#fff",
    fontSize: 18,
    fontWeight: 900,
    textAlign: "left",
    cursor: "pointer",
  },
  back: { padding: 12, borderRadius: 14, background: "#222", color: "#fff", border: "1px solid #333", fontWeight: 900, cursor: "pointer" },
  form: { display: "grid", gap: 14 },
  formSection: { color: "#ff8a00", fontWeight: 900, margin: "8px 0 0", fontSize: 14 },
  label: { display: "grid", gap: 6, fontWeight: 900, color: "#fff" },
  input: {
    padding: 16,
    borderRadius: 14,
    border: "1px solid #333",
    fontSize: 18,
    background: "#fff",
    color: "#111",
  },
  result: { marginTop: 16, padding: 20, background: "#1f1f1f", borderRadius: 20, border: "1px solid #333", fontWeight: 900 },
  resultLabel: { margin: "12px 0 4px", fontWeight: 900 },
  resultDetail: { margin: 0, color: "#ccc", lineHeight: 1.6, whiteSpace: "pre-line" },
  save: { width: "100%", marginTop: 12, padding: 18, borderRadius: 18, border: "none", background: "#ff6a00", color: "#fff", fontSize: 18, fontWeight: 900, cursor: "pointer" },
  pdf: { flex: "1 1 100px", padding: 12, borderRadius: 12, border: "none", background: "#2563eb", color: "#fff", fontWeight: 900, cursor: "pointer", fontSize: 15 },
  formActions: { display: "grid", gap: 10, marginTop: 20 },
  secondary: { flex: "1 1 80px", padding: 12, borderRadius: 12, border: "1px solid #333", background: "#333", color: "#fff", fontWeight: 900, cursor: "pointer", fontSize: 15 },
  listCard: { background: "#1f1f1f", border: "1px solid #333", borderRadius: 20, padding: 18, marginTop: 14 },
  sectionTitle: { margin: "0 0 12px", fontSize: 20 },
  priceGrid: { display: "grid", gap: 10 },
  priceList: { display: "grid", gap: 6, marginBottom: 12 },
  priceRow: { display: "flex", justifyContent: "space-between", gap: 12, margin: 0, fontWeight: 900 },
  rankRow: { display: "flex", justifyContent: "space-between", gap: 12, margin: "6px 0", fontWeight: 900, fontSize: 15 },
  rowActions: { display: "flex", flexWrap: "wrap", gap: 8, marginTop: 12 },
  delete: { flex: "1 1 80px", padding: 12, borderRadius: 12, border: "none", background: "#8b0000", color: "#fff", fontWeight: 900, cursor: "pointer", fontSize: 15 },
};
