export const s = {
  page: {
    minHeight: "100vh",
    background: "#111",
    color: "#fff",
    padding: "28px 20px 40px",
    fontFamily: "sans-serif",
    maxWidth: 520,
    margin: "0 auto",
    width: "100%",
    boxSizing: "border-box",
  },
  kicker: { color: "#ff8a00", fontWeight: 900, margin: 0, fontSize: 13 },
  title: { fontSize: 32, margin: "4px 0 24px", fontWeight: 900, letterSpacing: "-0.02em" },
  sub: { color: "#888", fontWeight: 700, margin: "0 0 20px", fontSize: 14 },
  muted: { color: "#888", margin: 0, fontSize: 14 },
  hint: { color: "#666", margin: 0, fontSize: 13, fontWeight: 700 },
  card: {
    background: "#ff6a00",
    borderRadius: 24,
    padding: "28px 24px",
    margin: "0 0 16px",
  },
  cardLabel: { margin: 0, fontWeight: 900, fontSize: 14, opacity: 0.95 },
  cardValue: { margin: "10px 0 0", fontSize: 40, fontWeight: 900, lineHeight: 1.1 },
  cardSub: { margin: "8px 0 0", color: "#fff7ed", fontWeight: 700, fontSize: 14 },
  dashGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 12,
    marginBottom: 28,
  },
  miniCard: {
    background: "#1a1a1a",
    border: "1px solid #2a2a2a",
    borderRadius: 20,
    padding: "20px 18px",
  },
  miniLabel: { margin: 0, color: "#888", fontSize: 13, fontWeight: 900 },
  miniCount: {
    margin: "10px 0 0",
    fontSize: 26,
    fontWeight: 900,
    lineHeight: 1.2,
    wordBreak: "break-all",
  },
  menuGroup: { display: "grid", gap: 12, marginTop: 8 },
  btn: {
    width: "100%",
    padding: "20px 22px",
    borderRadius: 18,
    border: "1px solid #2a2a2a",
    background: "#1a1a1a",
    color: "#fff",
    fontSize: 18,
    fontWeight: 900,
    textAlign: "left",
    cursor: "pointer",
  },
  btnPrimary: {
    width: "100%",
    padding: "22px 22px",
    borderRadius: 18,
    border: "none",
    background: "#ff6a00",
    color: "#fff",
    fontSize: 20,
    fontWeight: 900,
    textAlign: "center",
    cursor: "pointer",
  },
  back: {
    padding: "12px 16px",
    borderRadius: 14,
    background: "#1a1a1a",
    color: "#fff",
    border: "1px solid #2a2a2a",
    fontWeight: 900,
    cursor: "pointer",
    fontSize: 15,
    marginBottom: 8,
  },
  form: { display: "grid", gap: 16 },
  formSection: { color: "#ff8a00", fontWeight: 900, margin: "4px 0 0", fontSize: 13 },
  label: { display: "grid", gap: 8, fontWeight: 900, color: "#fff", fontSize: 14 },
  input: {
    padding: "18px 16px",
    borderRadius: 14,
    border: "1px solid #333",
    fontSize: 20,
    fontWeight: 700,
    background: "#fff",
    color: "#111",
  },
  result: {
    padding: "20px 18px",
    background: "#141414",
    borderRadius: 18,
    border: "1px solid #2a2a2a",
  },
  resultLabel: { margin: "0 0 6px", fontWeight: 900, fontSize: 13, color: "#888" },
  resultDetail: { margin: 0, color: "#ccc", lineHeight: 1.5, whiteSpace: "pre-line", fontSize: 15 },
  statGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 16,
  },
  statItem: { display: "grid", gap: 6 },
  statValue: {
    margin: 0,
    fontSize: 28,
    fontWeight: 900,
    lineHeight: 1.15,
    wordBreak: "break-all",
  },
  blockSection: {
    marginTop: 20,
    padding: "22px 20px",
    background: "#1a1a1a",
    borderRadius: 22,
    border: "1px solid #2a2a2a",
    display: "grid",
    gap: 16,
  },
  blockTitle: {
    margin: 0,
    fontSize: 15,
    fontWeight: 900,
    color: "#ff8a00",
    letterSpacing: "0.06em",
  },
  blockDivider: {
    margin: 0,
    border: "none",
    borderTop: "1px solid #2a2a2a",
  },
  details: {
    border: "1px solid #2a2a2a",
    borderRadius: 16,
    overflow: "hidden",
    background: "#141414",
  },
  detailsSummary: {
    padding: "16px 18px",
    fontWeight: 900,
    fontSize: 15,
    cursor: "pointer",
    listStyle: "none",
    color: "#ccc",
  },
  detailsBody: {
    padding: "0 18px 18px",
    display: "grid",
    gap: 14,
    borderTop: "1px solid #2a2a2a",
  },
  save: {
    width: "100%",
    marginTop: 4,
    padding: "20px 18px",
    borderRadius: 18,
    border: "none",
    background: "#ff6a00",
    color: "#fff",
    fontSize: 18,
    fontWeight: 900,
    cursor: "pointer",
  },
  pdf: {
    flex: "1 1 120px",
    padding: "16px 14px",
    borderRadius: 14,
    border: "none",
    background: "#2563eb",
    color: "#fff",
    fontWeight: 900,
    cursor: "pointer",
    fontSize: 16,
  },
  formActions: { display: "grid", gap: 12, marginTop: 24 },
  secondary: {
    flex: "1 1 100px",
    padding: "16px 14px",
    borderRadius: 14,
    border: "1px solid #333",
    background: "#262626",
    color: "#fff",
    fontWeight: 900,
    cursor: "pointer",
    fontSize: 16,
  },
  editBtn: {
    width: "100%",
    padding: "16px 18px",
    borderRadius: 14,
    border: "none",
    background: "#ff6a00",
    color: "#fff",
    fontWeight: 900,
    cursor: "pointer",
    fontSize: 16,
  },
  listCard: {
    background: "#1a1a1a",
    border: "1px solid #2a2a2a",
    borderRadius: 22,
    padding: "22px 20px",
    marginTop: 16,
  },
  sectionTitle: { margin: "0 0 16px", fontSize: 22, fontWeight: 900 },
  priceGrid: { display: "grid", gap: 12 },
  twoColGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "10px 16px",
  },
  priceList: { display: "grid", gap: 8, marginBottom: 8 },
  priceRow: {
    display: "flex",
    justifyContent: "space-between",
    gap: 12,
    margin: 0,
    fontWeight: 900,
    fontSize: 14,
  },
  listRow: {
    display: "grid",
    gridTemplateColumns: "1fr auto",
    gap: "8px 16px",
    alignItems: "center",
    marginBottom: 4,
  },
  listMeta: { margin: "0 0 16px", color: "#888", fontSize: 15, fontWeight: 700 },
  listStats: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr 1fr",
    gap: 12,
    marginBottom: 16,
  },
  listStat: { display: "grid", gap: 4 },
  listStatLabel: { margin: 0, fontSize: 12, color: "#888", fontWeight: 900 },
  listStatValue: { margin: 0, fontSize: 18, fontWeight: 900 },
  rowActions: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10, marginTop: 4 },
  delete: {
    padding: "14px 16px",
    borderRadius: 14,
    border: "1px solid #442222",
    background: "transparent",
    color: "#ef4444",
    fontWeight: 900,
    cursor: "pointer",
    fontSize: 14,
  },
  readOnlyValue: {
    margin: 0,
    padding: "14px 16px",
    borderRadius: 14,
    background: "#141414",
    border: "1px solid #2a2a2a",
    fontSize: 22,
    fontWeight: 900,
  },
  billingBadge: {
    display: "inline-block",
    padding: "4px 10px",
    borderRadius: 999,
    background: "#3d2200",
    color: "#ff8a00",
    fontSize: 11,
    fontWeight: 900,
    marginLeft: 8,
    verticalAlign: "middle",
  },
  usageCard: {
    background: "#1a1a1a",
    border: "1px solid #2a2a2a",
    borderRadius: 20,
    padding: "20px 18px",
    marginBottom: 28,
    display: "grid",
    gap: 6,
  },
  usageCardCompact: {
    background: "#141414",
    border: "1px solid #2a2a2a",
    borderRadius: 16,
    padding: "16px 18px",
    marginBottom: 16,
    display: "grid",
    gap: 4,
  },
  usageTitle: { margin: "0 0 8px", fontWeight: 900, fontSize: 14, color: "#ff8a00" },
  usageRow: { margin: 0, fontWeight: 900, fontSize: 16 },
  usageNote: { margin: 0, color: "#666", fontSize: 12, fontWeight: 700 },
  usageBilling: { margin: "8px 0 0", fontWeight: 900, fontSize: 22 },
  modalOverlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,0.8)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
    zIndex: 1000,
  },
  modalCard: {
    background: "#1a1a1a",
    border: "1px solid #333",
    borderRadius: 22,
    padding: "24px 22px",
    maxWidth: 400,
    width: "100%",
  },
  modalMessage: {
    margin: "0 0 20px",
    whiteSpace: "pre-line",
    lineHeight: 1.7,
    fontWeight: 700,
    fontSize: 16,
  },
  modalActions: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 10,
  },
  cardHeaderRow: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 8,
  },
  planSectionTitle: {
    margin: "0 0 16px",
    fontSize: 15,
    fontWeight: 900,
    color: "#ff8a00",
  },
  planRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "baseline",
    gap: 16,
    padding: "10px 0",
    borderBottom: "1px solid #2a2a2a",
  },
  planLabel: { color: "#888", fontWeight: 900, fontSize: 14 },
  planValue: { fontWeight: 900, fontSize: 16, textAlign: "right" },
  planExample: { margin: "4px 0 12px", color: "#666", fontSize: 12, fontWeight: 700 },
  planTotal: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "baseline",
    marginTop: 16,
    paddingTop: 16,
    borderTop: "1px solid #333",
  },
  planTotalValue: { fontSize: 28, fontWeight: 900, color: "#ff8a00" },
  planNote: { margin: "16px 0 0", color: "#666", fontSize: 12, fontWeight: 700 },
  ceoCard: {
    background: "#1a1a1a",
    border: "1px solid #2a2a2a",
    borderRadius: 20,
    padding: "20px 18px",
    marginBottom: 28,
    display: "grid",
    gap: 12,
  },
  ceoComment: {
    margin: 0,
    fontWeight: 700,
    fontSize: 15,
    lineHeight: 1.7,
    color: "#ddd",
  },
  ceoCommentLocked: {
    margin: 0,
    color: "#666",
    fontSize: 14,
    fontWeight: 700,
  },
  proBadge: {
    display: "inline-block",
    padding: "4px 10px",
    borderRadius: 999,
    background: "#3d2200",
    color: "#ff8a00",
    fontSize: 11,
    fontWeight: 900,
    marginBottom: 8,
  },
};
