export const s = {
  page: {
    background: "#111",
    color: "#fff",
    padding: "28px 20px 40px",
    fontFamily: "sans-serif",
    maxWidth: 520,
    margin: "0 auto",
    width: "100%",
    boxSizing: "border-box",
  },
  kicker: { color: "#ff8a00", fontWeight: 900, margin: 0, fontSize: 13 },
  title: { fontSize: 32, margin: "4px 0 24px", fontWeight: 900, letterSpacing: "-0.02em" },
  sub: { color: "#888", fontWeight: 700, margin: "0 0 20px", fontSize: 14 },
  muted: { color: "#888", margin: 0, fontSize: 14 },
  hint: { color: "#666", margin: 0, fontSize: 13, fontWeight: 700 },
  card: {
    background: "#ff6a00",
    borderRadius: 24,
    padding: "28px 24px",
    margin: "0 0 16px",
  },
  cardLabel: { margin: 0, fontWeight: 900, fontSize: 14, opacity: 0.95 },
  cardValue: { margin: "10px 0 0", fontSize: 40, fontWeight: 900, lineHeight: 1.1 },
  cardSub: { margin: "8px 0 0", color: "#fff7ed", fontWeight: 700, fontSize: 14 },
  dashGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 12,
    marginBottom: 28,
  },
  miniCard: {
    background: "#1a1a1a",
    border: "1px solid #2a2a2a",
    borderRadius: 20,
    padding: "20px 18px",
  },
  miniLabel: { margin: 0, color: "#888", fontSize: 13, fontWeight: 900 },
  miniCount: {
    margin: "10px 0 0",
    fontSize: 26,
    fontWeight: 900,
    lineHeight: 1.2,
    wordBreak: "break-all",
  },
  menuGroup: { display: "grid", gap: 12, marginTop: 8 },
  btn: {
    width: "100%",
    padding: "20px 22px",
    borderRadius: 18,
    border: "1px solid #2a2a2a",
    background: "#1a1a1a",
    color: "#fff",
    fontSize: 18,
    fontWeight: 900,
    textAlign: "left",
    cursor: "pointer",
    touchAction: "manipulation",
    WebkitTapHighlightColor: "rgba(255, 122, 0, 0.25)",
  },
  btnPrimary: {
    width: "100%",
    padding: "22px 22px",
    borderRadius: 18,
    border: "none",
    background: "#ff6a00",
    color: "#fff",
    fontSize: 20,
    fontWeight: 900,
    textAlign: "center",
    cursor: "pointer",
    touchAction: "manipulation",
    WebkitTapHighlightColor: "rgba(255, 122, 0, 0.25)",
  },
  back: {
    padding: "12px 16px",
    borderRadius: 14,
    background: "#1a1a1a",
    color: "#fff",
    border: "1px solid #2a2a2a",
    fontWeight: 900,
    cursor: "pointer",
    fontSize: 15,
    marginBottom: 8,
    touchAction: "manipulation",
    WebkitTapHighlightColor: "rgba(255, 122, 0, 0.25)",
  },
  form: { display: "grid", gap: 16 },
  formSection: { color: "#ff8a00", fontWeight: 900, margin: "4px 0 0", fontSize: 13 },
  label: { display: "grid", gap: 8, fontWeight: 900, color: "#fff", fontSize: 14 },
  input: {
    padding: "18px 16px",
    borderRadius: 14,
    border: "1px solid #333",
    fontSize: 20,
    fontWeight: 700,
    background: "#fff",
    color: "#111",
    touchAction: "manipulation",
    WebkitTapHighlightColor: "rgba(255, 122, 0, 0.25)",
  },
  result: {
    padding: "20px 18px",
    background: "#141414",
    borderRadius: 18,
    border: "1px solid #2a2a2a",
  },
  resultLabel: { margin: "0 0 6px", fontWeight: 900, fontSize: 13, color: "#888" },
  resultDetail: { margin: 0, color: "#ccc", lineHeight: 1.5, whiteSpace: "pre-line", fontSize: 15 },
  statGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 16,
  },
  statItem: { display: "grid", gap: 6 },
  statValue: {
    margin: 0,
    fontSize: 28,
    fontWeight: 900,
    lineHeight: 1.15,
    wordBreak: "break-all",
  },
  blockSection: {
    marginTop: 20,
    padding: "22px 20px",
    background: "#1a1a1a",
    borderRadius: 22,
    border: "1px solid #2a2a2a",
    display: "grid",
    gap: 16,
  },
  blockTitle: {
    margin: 0,
    fontSize: 15,
    fontWeight: 900,
    color: "#ff8a00",
    letterSpacing: "0.06em",
  },
  blockDivider: {
    margin: 0,
    border: "none",
    borderTop: "1px solid #2a2a2a",
  },
  details: {
    border: "1px solid #2a2a2a",
    borderRadius: 16,
    background: "#141414",
  },
  detailsSummary: {
    width: "100%",
    padding: "16px 18px",
    fontWeight: 900,
    fontSize: 15,
    cursor: "pointer",
    listStyle: "none",
    color: "#ccc",
    textAlign: "left",
    background: "transparent",
    border: 0,
    borderRadius: 16,
    touchAction: "manipulation",
    WebkitTapHighlightColor: "rgba(255, 122, 0, 0.25)",
  },
  detailsBody: {
    padding: "0 18px 18px",
    display: "grid",
    gap: 14,
    borderTop: "1px solid #2a2a2a",
  },
  save: {
    width: "100%",
    marginTop: 4,
    padding: "20px 18px",
    borderRadius: 18,
    border: "none",
    background: "#ff6a00",
    color: "#fff",
    fontSize: 18,
    fontWeight: 900,
    cursor: "pointer",
  },
  pdf: {
    flex: "1 1 120px",
    padding: "16px 14px",
    borderRadius: 14,
    border: "none",
    background: "#2563eb",
    color: "#fff",
    fontWeight: 900,
    cursor: "pointer",
    fontSize: 16,
  },
  formActions: { display: "grid", gap: 12, marginTop: 24 },
  secondary: {
    flex: "1 1 100px",
    padding: "16px 14px",
    borderRadius: 14,
    border: "1px solid #333",
    background: "#262626",
    color: "#fff",
    fontWeight: 900,
    cursor: "pointer",
    fontSize: 16,
  },
  editBtn: {
    width: "100%",
    padding: "16px 18px",
    borderRadius: 14,
    border: "none",
    background: "#ff6a00",
    color: "#fff",
    fontWeight: 900,
    cursor: "pointer",
    fontSize: 16,
  },
  listCard: {
    background: "#1a1a1a",
    border: "1px solid #2a2a2a",
    borderRadius: 22,
    padding: "22px 20px",
    marginTop: 16,
  },
  sectionTitle: { margin: "0 0 16px", fontSize: 22, fontWeight: 900 },
  priceGrid: { display: "grid", gap: 12 },
  twoColGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "10px 16px",
  },
  priceList: { display: "grid", gap: 8, marginBottom: 8 },
  priceRow: {
    display: "flex",
    justifyContent: "space-between",
    gap: 12,
    margin: 0,
    fontWeight: 900,
    fontSize: 14,
  },
  listRow: {
    display: "grid",
    gridTemplateColumns: "1fr auto",
    gap: "8px 16px",
    alignItems: "center",
    marginBottom: 4,
  },
  listMeta: { margin: "0 0 16px", color: "#888", fontSize: 15, fontWeight: 700 },
  listStats: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr 1fr",
    gap: 12,
    marginBottom: 16,
  },
  listStat: { display: "grid", gap: 4 },
  listStatLabel: { margin: 0, fontSize: 12, color: "#888", fontWeight: 900 },
  listStatValue: { margin: 0, fontSize: 18, fontWeight: 900 },
  listCardHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 12,
    marginBottom: 8,
  },
  listCardTitleBlock: {
    display: "grid",
    gap: 6,
    flex: 1,
    minWidth: 0,
  },
  sendBtn: {
    flexShrink: 0,
    padding: "12px 16px",
    borderRadius: 14,
    border: "1px solid #333",
    background: "#222",
    color: "#fff",
    fontWeight: 900,
    fontSize: 15,
    cursor: "pointer",
    whiteSpace: "nowrap",
  },
  invoiceSendBtn: {
    width: "100%",
    marginTop: 12,
    padding: "14px 16px",
    borderRadius: 14,
    border: "none",
    background: "#7c3aed",
    color: "#fff",
    fontWeight: 900,
    fontSize: 15,
    cursor: "pointer",
  },
  paymentStatusBadge: {
    margin: 0,
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    padding: "6px 10px",
    borderRadius: 999,
    background: "#222",
    color: "#f5f5f5",
    fontSize: 13,
    fontWeight: 800,
    width: "fit-content",
  },
  rowActions: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10, marginTop: 12 },
  pdfActionWrap: {
    display: "grid",
    gap: 10,
    marginTop: 12,
  },
  pdfActionGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 10,
  },
  pdfEstimateBtn: {
    padding: "14px 12px",
    borderRadius: 14,
    border: "none",
    background: "#2563eb",
    color: "#fff",
    fontWeight: 900,
    cursor: "pointer",
    fontSize: 15,
  },
  pdfInvoiceBtn: {
    padding: "14px 12px",
    borderRadius: 14,
    border: "none",
    background: "#7c3aed",
    color: "#fff",
    fontWeight: 900,
    cursor: "pointer",
    fontSize: 15,
  },
  pdfShareBtn: {
    padding: "14px 12px",
    borderRadius: 14,
    border: "none",
    background: "#16a34a",
    color: "#fff",
    fontWeight: 900,
    cursor: "pointer",
    fontSize: 15,
  },
  pdfDownloadBtn: {
    padding: "14px 12px",
    borderRadius: 14,
    border: "none",
    background: "#16a34a",
    color: "#fff",
    fontWeight: 900,
    cursor: "pointer",
    fontSize: 15,
  },
  pdfStatusText: {
    margin: "10px 0 0",
    color: "#888",
    fontSize: 13,
    lineHeight: 1.5,
    wordBreak: "break-all",
  },
  pdfErrorText: {
    margin: "10px 0 0",
    color: "#ef4444",
    fontSize: 13,
    lineHeight: 1.5,
  },
  copyBtn: {
    width: "100%",
    padding: "16px 12px",
    borderRadius: 14,
    border: "1px solid #444",
    background: "#1a1a1a",
    color: "#fff",
    fontWeight: 900,
    cursor: "pointer",
    fontSize: 15,
  },
  delete: {
    padding: "14px 16px",
    borderRadius: 14,
    border: "1px solid #442222",
    background: "transparent",
    color: "#ef4444",
    fontWeight: 900,
    cursor: "pointer",
    fontSize: 14,
  },
  readOnlyValue: {
    margin: 0,
    padding: "14px 16px",
    borderRadius: 14,
    background: "#141414",
    border: "1px solid #2a2a2a",
    fontSize: 22,
    fontWeight: 900,
  },
  billingBadge: {
    display: "inline-block",
    padding: "4px 10px",
    borderRadius: 999,
    background: "#3d2200",
    color: "#ff8a00",
    fontSize: 11,
    fontWeight: 900,
    marginLeft: 8,
    verticalAlign: "middle",
  },
  usageCard: {
    background: "#1a1a1a",
    border: "1px solid #2a2a2a",
    borderRadius: 20,
    padding: "20px 18px",
    marginBottom: 28,
    display: "grid",
    gap: 6,
  },
  usageCardCompact: {
    background: "#141414",
    border: "1px solid #2a2a2a",
    borderRadius: 16,
    padding: "16px 18px",
    marginBottom: 16,
    display: "grid",
    gap: 4,
  },
  usageTitle: { margin: "0 0 8px", fontWeight: 900, fontSize: 14, color: "#ff8a00" },
  usageRow: { margin: 0, fontWeight: 900, fontSize: 16 },
  usageNote: { margin: 0, color: "#666", fontSize: 12, fontWeight: 700 },
  usageBilling: { margin: "8px 0 0", fontWeight: 900, fontSize: 22 },
  modalOverlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,0.8)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
    zIndex: 1000,
    pointerEvents: "auto",
    touchAction: "manipulation",
    WebkitOverflowScrolling: "touch",
  },
  modalCard: {
    background: "#1a1a1a",
    border: "1px solid #333",
    borderRadius: 22,
    padding: "24px 22px",
    maxWidth: 400,
    width: "100%",
    pointerEvents: "auto",
  },
  modalMessage: {
    margin: "0 0 20px",
    whiteSpace: "pre-line",
    lineHeight: 1.7,
    fontWeight: 700,
    fontSize: 16,
  },
  modalActions: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 10,
  },
  sendSheet: {
    background: "#1a1a1a",
    border: "1px solid #333",
    borderRadius: 22,
    padding: "8px 22px 20px",
    maxWidth: 420,
    width: "100%",
    display: "grid",
    gap: 14,
  },
  sendSheetDivider: {
    height: 1,
    background: "#333",
    margin: "4px 0",
  },
  sendSheetTitle: {
    margin: 0,
    fontSize: 18,
    fontWeight: 900,
    textAlign: "center",
  },
  sendSheetSite: {
    margin: 0,
    color: "#888",
    fontSize: 14,
    fontWeight: 700,
    textAlign: "center",
  },
  sendMethodList: {
    display: "grid",
    gap: 10,
    marginTop: 4,
  },
  sendMethodOption: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "12px 14px",
    borderRadius: 14,
    background: "#141414",
    border: "1px solid #2a2a2a",
    fontWeight: 800,
    fontSize: 16,
    cursor: "pointer",
  },
  sendSheetActions: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 10,
    marginTop: 4,
  },
  sendSheetSubmit: {
    padding: "16px 14px",
    borderRadius: 14,
    border: "none",
    background: "#ff6a00",
    color: "#fff",
    fontWeight: 900,
    fontSize: 16,
    cursor: "pointer",
  },
  sendBtnWide: {
    width: "100%",
    padding: "14px 16px",
    borderRadius: 14,
    border: "1px solid #333",
    background: "#222",
    color: "#fff",
    fontWeight: 900,
    fontSize: 16,
    cursor: "pointer",
  },
  sendSheetInline: {
    display: "grid",
    gap: 12,
    marginTop: 4,
    padding: "8px 0 0",
  },
  sendMethodActions: {
    display: "grid",
    gap: 10,
  },
  sendMethodActionBtn: {
    padding: "14px 12px",
    borderRadius: 14,
    border: "none",
    background: "#262626",
    color: "#fff",
    fontWeight: 900,
    fontSize: 15,
    cursor: "pointer",
  },
  cardHeaderRow: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 8,
  },
  planSectionTitle: {
    margin: "0 0 16px",
    fontSize: 15,
    fontWeight: 900,
    color: "#ff8a00",
  },
  planRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "baseline",
    gap: 16,
    padding: "10px 0",
    borderBottom: "1px solid #2a2a2a",
  },
  planLabel: { color: "#888", fontWeight: 900, fontSize: 14 },
  planValue: { fontWeight: 900, fontSize: 16, textAlign: "right" },
  planExample: { margin: "4px 0 12px", color: "#666", fontSize: 12, fontWeight: 700 },
  planTotal: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "baseline",
    marginTop: 16,
    paddingTop: 16,
    borderTop: "1px solid #333",
  },
  planTotalValue: { fontSize: 28, fontWeight: 900, color: "#ff8a00" },
  planNote: { margin: "16px 0 0", color: "#666", fontSize: 12, fontWeight: 700 },
  ceoCard: {
    background: "#1a1a1a",
    border: "1px solid #2a2a2a",
    borderRadius: 20,
    padding: "20px 18px",
    marginBottom: 28,
    display: "grid",
    gap: 12,
  },
  ceoComment: {
    margin: 0,
    fontWeight: 700,
    fontSize: 15,
    lineHeight: 1.7,
    color: "#ddd",
  },
  ceoCommentLocked: {
    margin: 0,
    color: "#666",
    fontSize: 14,
    fontWeight: 700,
  },
  proBadge: {
    display: "inline-block",
    padding: "4px 10px",
    borderRadius: 999,
    background: "#3d2200",
    color: "#ff8a00",
    fontSize: 11,
    fontWeight: 900,
    marginBottom: 8,
  },
  currentPlanCard: {
    background: "linear-gradient(145deg, #1c1c1e 0%, #141416 100%)",
    border: "1px solid #3a3a3c",
    borderRadius: 22,
    padding: "22px 20px",
    marginBottom: 20,
  },
  currentPlanLabel: {
    margin: 0,
    color: "#888",
    fontSize: 13,
    fontWeight: 700,
    letterSpacing: "0.04em",
  },
  currentPlanName: {
    margin: "8px 0 0",
    fontSize: 34,
    fontWeight: 700,
    letterSpacing: "-0.03em",
  },
  currentPlanSub: {
    margin: "4px 0 0",
    color: "#666",
    fontSize: 13,
    fontWeight: 700,
  },
  pricingKicker: {
    margin: "0 0 4px",
    color: "#888",
    fontSize: 13,
    fontWeight: 700,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
  },
  pricingStack: {
    display: "grid",
    gap: 16,
  },
  pricingCard: {
    background: "linear-gradient(160deg, #1c1c1e 0%, #161618 100%)",
    border: "1px solid #3a3a3c",
    borderRadius: 24,
    padding: "28px 24px",
    boxShadow: "0 8px 32px rgba(0,0,0,0.35)",
  },
  pricingCardFeatured: {
    border: "1px solid #ff8a00",
    boxShadow: "0 12px 40px rgba(255,106,0,0.15)",
  },
  pricingCardCurrent: {
    background: "linear-gradient(160deg, #222 0%, #1a1a1a 100%)",
  },
  pricingPopular: {
    margin: "0 0 12px",
    color: "#ff8a00",
    fontSize: 13,
    fontWeight: 700,
    letterSpacing: "0.02em",
  },
  pricingCurrentBadge: {
    display: "inline-block",
    margin: "0 0 12px",
    padding: "5px 12px",
    borderRadius: 999,
    background: "#2a2a2a",
    color: "#aaa",
    fontSize: 12,
    fontWeight: 700,
  },
  pricingName: {
    margin: 0,
    fontSize: 22,
    fontWeight: 700,
    letterSpacing: "-0.02em",
  },
  pricingPriceRow: {
    display: "flex",
    alignItems: "baseline",
    gap: 4,
    marginTop: 12,
    marginBottom: 20,
  },
  pricingPrice: {
    fontSize: 40,
    fontWeight: 700,
    letterSpacing: "-0.04em",
    lineHeight: 1,
  },
  pricingPriceSub: {
    color: "#888",
    fontSize: 16,
    fontWeight: 600,
  },
  pricingFeatures: {
    margin: "0 0 24px",
    padding: 0,
    listStyle: "none",
    display: "grid",
    gap: 10,
    color: "#ccc",
    fontSize: 15,
    fontWeight: 500,
    lineHeight: 1.5,
  },
  pricingBtnPrimary: {
    width: "100%",
    padding: "16px 18px",
    borderRadius: 14,
    border: "none",
    background: "#ff6a00",
    color: "#fff",
    fontSize: 16,
    fontWeight: 700,
    cursor: "pointer",
  },
  pricingBtnSecondary: {
    width: "100%",
    padding: "16px 18px",
    borderRadius: 14,
    border: "none",
    background: "#f5f5f7",
    color: "#111",
    fontSize: 16,
    fontWeight: 700,
    cursor: "pointer",
  },
  pricingBtnOutline: {
    width: "100%",
    padding: "16px 18px",
    borderRadius: 14,
    border: "1px solid #555",
    background: "transparent",
    color: "#fff",
    fontSize: 16,
    fontWeight: 700,
    cursor: "pointer",
  },
  pricingBtnCurrent: {
    width: "100%",
    padding: "16px 18px",
    borderRadius: 14,
    border: "1px solid #3a3a3c",
    background: "#2a2a2a",
    color: "#888",
    fontSize: 16,
    fontWeight: 700,
    cursor: "default",
  },
  ceoDashKicker: {
    margin: "0 0 20px",
    color: "#888",
    fontSize: 13,
    fontWeight: 700,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
  },
  ceoHeroCard: {
    background: "linear-gradient(145deg, #ff6a00 0%, #e85d00 100%)",
    borderRadius: 28,
    padding: "32px 28px",
    marginBottom: 16,
    boxShadow: "0 16px 48px rgba(255,106,0,0.25)",
  },
  ceoHeroLabel: {
    margin: 0,
    fontSize: 15,
    fontWeight: 700,
    opacity: 0.92,
  },
  ceoHeroValue: {
    margin: "12px 0 0",
    fontSize: 48,
    fontWeight: 700,
    letterSpacing: "-0.04em",
    lineHeight: 1,
  },
  ceoMetricGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 12,
  },
  ceoMetricCard: {
    background: "linear-gradient(160deg, #1c1c1e 0%, #161618 100%)",
    border: "1px solid #3a3a3c",
    borderRadius: 22,
    padding: "24px 20px",
  },
  ceoMetricCardLabel: {
    margin: 0,
    color: "#888",
    fontSize: 13,
    fontWeight: 700,
  },
  ceoMetricCardValue: {
    margin: "10px 0 0",
    fontSize: 28,
    fontWeight: 700,
    letterSpacing: "-0.03em",
    lineHeight: 1.1,
    wordBreak: "break-all",
  },
  ceoTargetCard: {
    background: "#1a1a1a",
    border: "1px solid #2a2a2a",
    borderRadius: 22,
    padding: "22px 20px",
    marginTop: 12,
    display: "grid",
    gap: 14,
  },
  ceoMetricRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "baseline",
    gap: 16,
  },
  ceoMetricLabel: {
    color: "#888",
    fontSize: 15,
    fontWeight: 700,
  },
  ceoMetricValue: {
    fontSize: 24,
    fontWeight: 700,
    letterSpacing: "-0.02em",
  },
  ceoMetricValueAccent: {
    fontSize: 28,
    fontWeight: 700,
    color: "#ff8a00",
    letterSpacing: "-0.02em",
  },
  ceoDashDivider: {
    margin: "28px 0",
    border: "none",
    borderTop: "1px solid #2a2a2a",
  },
  ceoDashSection: {
    display: "grid",
    gap: 16,
  },
  ceoDashSectionTitle: {
    margin: 0,
    fontSize: 15,
    fontWeight: 700,
    color: "#ff8a00",
    letterSpacing: "0.04em",
  },
  ceoCommentList: {
    margin: 0,
    padding: 0,
    listStyle: "none",
    display: "grid",
    gap: 14,
  },
  ceoCommentItem: {
    margin: 0,
    padding: "0 0 0 1em",
    textIndent: "-1em",
    fontSize: 16,
    fontWeight: 600,
    lineHeight: 1.7,
    color: "#eee",
  },
  ceoRankList: {
    margin: 0,
    padding: 0,
    listStyle: "none",
    display: "grid",
    gap: 12,
  },
  ceoRankItem: {
    display: "grid",
    gridTemplateColumns: "auto 1fr auto",
    gap: "8px 14px",
    alignItems: "center",
    padding: "18px 20px",
    background: "#1a1a1a",
    border: "1px solid #2a2a2a",
    borderRadius: 18,
  },
  ceoRankPlace: {
    color: "#ff8a00",
    fontSize: 14,
    fontWeight: 700,
    minWidth: 32,
  },
  ceoRankName: {
    fontSize: 17,
    fontWeight: 700,
  },
  ceoRankValue: {
    fontSize: 16,
    fontWeight: 700,
    color: "#ccc",
  },
  ceoEmptyText: {
    margin: 0,
    color: "#666",
    fontSize: 15,
    fontWeight: 600,
  },
  ceoRecentList: {
    display: "grid",
    gap: 12,
  },
  ceoRecentItem: {
    padding: "20px 20px",
    background: "#1a1a1a",
    border: "1px solid #2a2a2a",
    borderRadius: 18,
  },
  ceoRecentTitle: {
    margin: 0,
    fontSize: 18,
    fontWeight: 700,
  },
  ceoRecentMeta: {
    margin: "6px 0 0",
    color: "#888",
    fontSize: 14,
    fontWeight: 600,
  },
  ceoRecentStats: {
    display: "flex",
    justifyContent: "space-between",
    marginTop: 12,
    fontSize: 17,
    fontWeight: 700,
    color: "#ff8a00",
  },
  ceoNav: {
    display: "grid",
    gap: 12,
    marginTop: 32,
    paddingBottom: 8,
  },
  homeTitle: {
    margin: "0 0 24px",
    fontSize: 15,
    fontWeight: 700,
    color: "#888",
    letterSpacing: "0.06em",
  },
  dashHeader: {
    marginBottom: 4,
  },
  dashBrand: {
    margin: 0,
    fontSize: 28,
    fontWeight: 700,
    letterSpacing: "-0.03em",
  },
  dashPlanRow: {
    margin: "10px 0 0",
    display: "flex",
    alignItems: "baseline",
    gap: 10,
  },
  dashPlanLabel: {
    color: "#666",
    fontSize: 14,
    fontWeight: 700,
  },
  dashPlanName: {
    color: "#ff8a00",
    fontSize: 18,
    fontWeight: 700,
  },
  homeDivider: {
    margin: "28px 0",
    border: "none",
    borderTop: "1px solid #2a2a2a",
  },
  homeHeroCard: {
    background: "linear-gradient(145deg, #ff6a00 0%, #e85d00 100%)",
    borderRadius: 28,
    padding: "36px 28px",
    marginBottom: 16,
    boxShadow: "0 16px 48px rgba(255,106,0,0.22)",
  },
  homeHeroLabel: {
    margin: 0,
    fontSize: 15,
    fontWeight: 700,
    opacity: 0.92,
  },
  homeHeroValue: {
    margin: "14px 0 0",
    fontSize: 52,
    fontWeight: 700,
    letterSpacing: "-0.04em",
    lineHeight: 1,
  },
  homeMetricStack: {
    display: "grid",
    gap: 12,
    marginBottom: 28,
  },
  homeMetricCard: {
    background: "linear-gradient(160deg, #1c1c1e 0%, #161618 100%)",
    border: "1px solid #3a3a3c",
    borderRadius: 22,
    padding: "24px 22px",
  },
  homeMetricCardAccent: {
    border: "1px solid #ff8a00",
    boxShadow: "0 8px 28px rgba(255,106,0,0.12)",
  },
  homeMetricLabel: {
    margin: 0,
    color: "#888",
    fontSize: 14,
    fontWeight: 700,
  },
  homeMetricValue: {
    margin: "10px 0 0",
    fontSize: 32,
    fontWeight: 700,
    letterSpacing: "-0.03em",
    lineHeight: 1.1,
    wordBreak: "break-all",
  },
  homeMetricValueAccent: {
    margin: "10px 0 0",
    fontSize: 36,
    fontWeight: 700,
    color: "#ff8a00",
    letterSpacing: "-0.03em",
    lineHeight: 1.1,
    wordBreak: "break-all",
  },
  homeSection: {
    marginTop: 28,
    display: "grid",
    gap: 16,
  },
  homeSectionTitle: {
    margin: 0,
    fontSize: 15,
    fontWeight: 700,
    color: "#ff8a00",
    letterSpacing: "0.04em",
  },
  quickEstimateGroups: {
    display: "grid",
    gap: 20,
  },
  quickEstimateGroup: {
    display: "grid",
    gap: 10,
  },
  quickEstimateClient: {
    margin: 0,
    fontSize: 17,
    fontWeight: 700,
    color: "#f5f5f5",
  },
  quickEstimateItems: {
    display: "flex",
    flexWrap: "wrap",
    gap: 10,
    paddingLeft: 8,
  },
  quickEstimateBtn: {
    padding: "12px 18px",
    background: "#1a1a1a",
    border: "1px solid #333",
    borderRadius: 14,
    color: "#f5f5f5",
    fontSize: 15,
    fontWeight: 600,
    cursor: "pointer",
  },
  quickEstimateFormHeader: {
    margin: "0 0 8px",
    padding: "18px 20px",
    background: "#1a1a1a",
    border: "1px solid #2a2a2a",
    borderRadius: 18,
    display: "grid",
    gap: 8,
  },
  quickEstimateFormMeta: {
    margin: 0,
    fontSize: 17,
    fontWeight: 700,
  },
  quickEstimateFormHint: {
    margin: 0,
    color: "#888",
    fontSize: 14,
    lineHeight: 1.5,
  },
  homeRankList: {
    margin: 0,
    padding: 0,
    listStyle: "none",
    display: "grid",
    gap: 12,
  },
  homeRankItem: {
    display: "grid",
    gap: 8,
    padding: "22px 22px",
    background: "#1a1a1a",
    border: "1px solid #2a2a2a",
    borderRadius: 20,
  },
  homeRankMain: {
    display: "grid",
    gridTemplateColumns: "auto 1fr",
    gap: 16,
    alignItems: "center",
  },
  homeRankPlace: {
    color: "#ff8a00",
    fontSize: 22,
    fontWeight: 700,
    minWidth: 28,
  },
  homeRankName: {
    fontSize: 20,
    fontWeight: 700,
  },
  homeRankRate: {
    margin: "0 0 0 44px",
    color: "#888",
    fontSize: 15,
    fontWeight: 700,
  },
  homeStatusGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 12,
  },
  homeStatusItem: {
    display: "grid",
    gap: 6,
    padding: "18px 16px",
    background: "#1a1a1a",
    border: "1px solid #2a2a2a",
    borderRadius: 18,
  },
  homeStatusLabel: {
    margin: 0,
    fontSize: 14,
    fontWeight: 800,
    color: "#aaa",
  },
  homeStatusValue: {
    margin: 0,
    fontSize: 24,
    fontWeight: 900,
  },
  paymentBlock: {
    marginTop: 16,
    padding: "18px 16px",
    background: "#141414",
    border: "1px solid #2a2a2a",
    borderRadius: 16,
    display: "grid",
    gap: 12,
  },
  paymentBlockTitle: {
    margin: 0,
    fontSize: 13,
    fontWeight: 900,
    color: "#ff8a00",
    letterSpacing: "0.04em",
  },
  paymentFlow: {
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
    alignItems: "center",
  },
  paymentStep: {
    display: "inline-block",
    padding: "6px 10px",
    borderRadius: 999,
    background: "#222",
    color: "#666",
    fontSize: 12,
    fontWeight: 700,
  },
  paymentStepActive: {
    background: "#3d2200",
    color: "#ff8a00",
  },
  paymentStepDone: {
    background: "#1f2937",
    color: "#9ca3af",
  },
  paymentArrow: {
    color: "#444",
    fontSize: 12,
    marginRight: 6,
  },
  paymentActions: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 10,
  },
  paymentAdvanceBtn: {
    padding: "14px 12px",
    borderRadius: 14,
    border: "1px solid #333",
    background: "#262626",
    color: "#fff",
    fontWeight: 900,
    fontSize: 14,
    cursor: "pointer",
  },
  paymentPaidBtn: {
    padding: "14px 12px",
    borderRadius: 14,
    border: "1px solid #ff8a00",
    background: "transparent",
    color: "#ff8a00",
    fontWeight: 900,
    fontSize: 14,
    cursor: "pointer",
  },
  paymentPaidDone: {
    padding: "14px 12px",
    borderRadius: 14,
    border: "1px solid #2a2a2a",
    background: "#1f1f1f",
    color: "#666",
    fontWeight: 900,
    fontSize: 14,
    cursor: "default",
  },
  paymentCurrent: {
    margin: 0,
    color: "#888",
    fontSize: 13,
    fontWeight: 700,
  },
  estimatePage: {
    background: "#111",
    color: "#fff",
    padding: "24px 20px 56px",
    fontFamily: "-apple-system, BlinkMacSystemFont, sans-serif",
    maxWidth: 520,
    margin: "0 auto",
    width: "100%",
    boxSizing: "border-box",
  },
  estimatePageTitle: {
    fontSize: 28,
    margin: "0 0 32px",
    fontWeight: 700,
    letterSpacing: "-0.03em",
  },
  estimateSection: {
    display: "grid",
    gap: 18,
  },
  estimateSectionTitle: {
    margin: 0,
    fontSize: 14,
    fontWeight: 700,
    color: "#ff8a00",
    letterSpacing: "0.04em",
  },
  estimateSectionBody: {
    display: "grid",
    gap: 20,
  },
  customerPreview: {
    padding: "14px 16px",
    borderRadius: 12,
    background: "#151515",
    border: "1px solid #2a2a2a",
    display: "grid",
    gap: 6,
  },
  customerPreviewTitle: {
    margin: 0,
    fontSize: 12,
    fontWeight: 900,
    color: "#ff8a00",
    letterSpacing: "0.04em",
  },
  customerPreviewLine: {
    margin: 0,
    fontSize: 13,
    color: "#d6d6d6",
    lineHeight: 1.5,
  },
  partnerEvaluationCard: {
    marginTop: 16,
    padding: "16px 18px",
    borderRadius: 12,
    background: "#121212",
    border: "1px solid #2f2f2f",
    display: "grid",
    gap: 12,
  },
  partnerEvaluationHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
    flexWrap: "wrap",
  },
  partnerEvaluationStars: {
    margin: 0,
    fontSize: 18,
    letterSpacing: "0.08em",
    color: "#ffb020",
    fontWeight: 900,
  },
  partnerEvaluationNote: {
    margin: 0,
    fontSize: 11,
    color: "#888",
    lineHeight: 1.5,
  },
  recommendedPartnerItem: {
    display: "grid",
    gap: 6,
    padding: "12px 0",
    borderBottom: "1px solid #2a2a2a",
  },
  recommendedPartnerMain: {
    display: "flex",
    alignItems: "center",
    gap: 10,
  },
  recommendedPartnerMeta: {
    margin: 0,
    fontSize: 13,
    color: "#bdbdbd",
  },
  estimateDivider: {
    margin: "36px 0",
    border: "none",
    borderTop: "1px solid #2a2a2a",
  },
  estimateLabel: {
    display: "grid",
    gap: 10,
    fontWeight: 700,
    color: "#fff",
    fontSize: 15,
  },
  estimateInput: {
    width: "100%",
    padding: "18px 16px",
    borderRadius: 16,
    border: "1px solid #333",
    background: "#141414",
    color: "#fff",
    fontSize: 18,
    fontWeight: 600,
    boxSizing: "border-box",
    minHeight: 56,
  },
  laborStepperRow: {
    display: "grid",
    gridTemplateColumns: "64px 1fr 64px",
    gap: 10,
    alignItems: "stretch",
  },
  laborStepperBtn: {
    minHeight: 64,
    borderRadius: 16,
    border: "1px solid #333",
    background: "#1a1a1a",
    color: "#fff",
    fontSize: 28,
    fontWeight: 700,
    cursor: "pointer",
    lineHeight: 1,
  },
  laborStepperValueWrap: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    minHeight: 64,
    padding: "0 12px",
    borderRadius: 16,
    border: "1px solid #333",
    background: "#141414",
  },
  laborStepperInput: {
    width: 56,
    border: "none",
    background: "transparent",
    color: "#fff",
    fontSize: 24,
    fontWeight: 700,
    textAlign: "right",
    outline: "none",
    padding: 0,
  },
  laborStepperSuffix: {
    fontSize: 18,
    fontWeight: 700,
    color: "#ccc",
    whiteSpace: "nowrap",
  },
  estimateReadonly: {
    padding: "16px 18px",
    background: "#141414",
    borderRadius: 16,
    border: "1px solid #2a2a2a",
  },
  estimateReadonlyLarge: {
    padding: "20px 18px",
    background: "#141414",
    borderRadius: 18,
    border: "1px solid #333",
  },
  estimateReadonlyLabel: {
    margin: "0 0 6px",
    fontSize: 13,
    fontWeight: 700,
    color: "#888",
  },
  estimateReadonlyValue: {
    margin: 0,
    fontSize: 22,
    fontWeight: 700,
    letterSpacing: "-0.02em",
  },
  estimateReadonlyValueLarge: {
    margin: 0,
    fontSize: 28,
    fontWeight: 700,
    letterSpacing: "-0.03em",
    color: "#ff8a00",
  },
  estimateApplyBtn: {
    width: "100%",
    padding: "20px 16px",
    borderRadius: 18,
    border: "1px solid #ff8a00",
    background: "transparent",
    color: "#ff8a00",
    fontSize: 18,
    fontWeight: 700,
    cursor: "pointer",
    minHeight: 56,
  },
  estimateDetailToggleBtn: {
    width: "100%",
    padding: "16px 16px",
    borderRadius: 16,
    border: "1px solid #333",
    background: "#141414",
    color: "#ccc",
    fontSize: 16,
    fontWeight: 700,
    cursor: "pointer",
    minHeight: 52,
  },
  estimateResultSubGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 12,
  },
  estimateHeroGrid: {
    display: "grid",
    gap: 12,
    marginTop: 4,
  },
  estimateHeroCard: {
    padding: "24px 22px",
    background: "linear-gradient(160deg, #1c1c1e 0%, #141416 100%)",
    border: "2px solid #2a2a2a",
    borderRadius: 22,
  },
  estimateHeroLabel: {
    margin: "0 0 10px",
    fontSize: 13,
    fontWeight: 700,
    color: "#888",
  },
  estimateHeroValue: {
    margin: 0,
    fontSize: 36,
    fontWeight: 700,
    letterSpacing: "-0.03em",
    lineHeight: 1.1,
    wordBreak: "break-all",
  },
  estimateActions: {
    display: "grid",
    gap: 14,
    marginTop: 28,
    paddingBottom: 12,
  },
  estimateInvoiceBtn: {
    width: "100%",
    padding: "20px 18px",
    borderRadius: 18,
    border: "none",
    background: "#374151",
    color: "#fff",
    fontWeight: 700,
    fontSize: 18,
    cursor: "pointer",
  },
  estimateFieldLabel: {
    display: "block",
    fontWeight: 700,
    color: "#fff",
    fontSize: 14,
  },
  cardButtonRow: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 12,
  },
  cardButton: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    minHeight: 88,
    padding: "18px 12px",
    borderRadius: 20,
    border: "1px solid #333",
    background: "#141414",
    color: "#888",
    fontSize: 16,
    fontWeight: 700,
    cursor: "pointer",
    textAlign: "center",
  },
  cardButtonIcon: {
    fontSize: 28,
    lineHeight: 1,
  },
  cardButtonActive: {
    border: "2px solid #ff8a00",
    background: "linear-gradient(160deg, #2a1800 0%, #1a1000 100%)",
    color: "#fff",
    boxShadow: "0 8px 24px rgba(255,106,0,0.15)",
  },
  estimateHeroDivider: {
    height: 1,
    background: "linear-gradient(90deg, transparent, #444 20%, #444 80%, transparent)",
    margin: "4px 0",
  },
  estimateCostHero: {
    padding: "8px 4px 12px",
    textAlign: "center",
  },
  estimateCostHeroLabel: {
    margin: "12px 0 10px",
    fontSize: 14,
    fontWeight: 700,
    color: "#888",
    letterSpacing: "0.06em",
  },
  estimateCostHeroValue: {
    margin: "0 0 12px",
    fontSize: 44,
    fontWeight: 700,
    letterSpacing: "-0.04em",
    color: "#ff8a00",
    lineHeight: 1.05,
  },
  estimateResultCard: {
    marginTop: 36,
    padding: "8px 4px 12px",
    textAlign: "center",
  },
  estimateResultRow: {
    marginBottom: 20,
  },
  estimateResultRowLabel: {
    margin: "0 0 8px",
    fontSize: 14,
    fontWeight: 700,
    color: "#888",
    letterSpacing: "0.04em",
  },
  estimateResultRowValue: {
    margin: 0,
    fontSize: 30,
    fontWeight: 700,
    letterSpacing: "-0.03em",
    lineHeight: 1.1,
  },
  estimateResultHero: {
    margin: "28px 0",
  },
  estimateResultHeroLabel: {
    margin: "0 0 10px",
    fontSize: 15,
    fontWeight: 700,
    color: "#aaa",
    letterSpacing: "0.06em",
  },
  estimateResultHeroValue: {
    margin: 0,
    fontSize: 56,
    fontWeight: 700,
    letterSpacing: "-0.04em",
    lineHeight: 1,
  },
  estimateResultJudgment: {
    margin: "32px 0 16px",
  },
  estimateResultJudgmentValue: {
    margin: 0,
    fontSize: 40,
    fontWeight: 700,
    letterSpacing: "-0.02em",
    lineHeight: 1.15,
  },
  estimateAiComment: {
    marginTop: 28,
    padding: "22px 20px",
    borderRadius: 22,
    background: "#141414",
    border: "1px solid #2a2a2a",
  },
  estimateAiCommentTitle: {
    margin: "0 0 12px",
    fontSize: 16,
    fontWeight: 700,
    color: "#fff",
  },
  estimateAiCommentText: {
    margin: 0,
    fontSize: 17,
    fontWeight: 600,
    lineHeight: 1.55,
    color: "#ccc",
  },
  toggleRow: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    fontWeight: 900,
    fontSize: 15,
    color: "#fff",
  },
  gpsPanel: {
    display: "grid",
    gap: 12,
    padding: "16px",
    background: "#141414",
    border: "1px solid #2a2a2a",
    borderRadius: 16,
  },
  gpsBtn: {
    width: "100%",
    padding: "16px 14px",
    borderRadius: 14,
    border: "none",
    background: "#ff6a00",
    color: "#fff",
    fontWeight: 900,
    fontSize: 15,
    cursor: "pointer",
  },
  gpsBtnOutline: {
    width: "100%",
    padding: "16px 14px",
    borderRadius: 14,
    border: "1px solid #555",
    background: "transparent",
    color: "#fff",
    fontWeight: 900,
    fontSize: 15,
    cursor: "pointer",
  },
  gpsBtnSecondary: {
    width: "100%",
    padding: "16px 14px",
    borderRadius: 14,
    border: "1px solid #333",
    background: "#262626",
    color: "#fff",
    fontWeight: 900,
    fontSize: 15,
    cursor: "pointer",
  },
  siteTransportBox: {
    display: "grid",
    gap: 12,
    padding: "16px",
    background: "#141414",
    border: "1px solid #2a2a2a",
    borderRadius: 16,
  },
  transportCalcBox: {
    padding: "20px 18px",
    background: "#141414",
    border: "1px solid #2a2a2a",
    borderRadius: 16,
    display: "grid",
    gap: 8,
  },
  transportSummaryLine: {
    margin: 0,
    fontSize: 16,
    fontWeight: 700,
    color: "#ccc",
    lineHeight: 1.5,
  },
  transportSummaryCost: {
    marginTop: 4,
    fontSize: 24,
    color: "#ff8a00",
    letterSpacing: "-0.02em",
  },
  radioGroup: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 10,
  },
  radioOption: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "16px 14px",
    borderRadius: 14,
    border: "1px solid #333",
    background: "#141414",
    fontWeight: 900,
    fontSize: 15,
    cursor: "pointer",
  },
  gpsMeta: {
    margin: 0,
    color: "#aaa",
    fontSize: 14,
    fontWeight: 700,
    lineHeight: 1.6,
  },
  gpsApiNotice: {
    margin: 0,
    padding: "12px 14px",
    borderRadius: 12,
    background: "#2a1a00",
    border: "1px solid #553300",
    color: "#ff8a00",
    fontSize: 14,
    fontWeight: 800,
    textAlign: "center",
  },
  gpsApiReady: {
    margin: 0,
    padding: "12px 14px",
    borderRadius: 12,
    background: "#141414",
    border: "1px solid #2a2a2a",
    color: "#888",
    fontSize: 13,
    fontWeight: 700,
    textAlign: "center",
  },
  gpsSummary: {
    display: "grid",
    gap: 8,
    paddingTop: 4,
  },
  gpsSummaryRow: {
    margin: 0,
    display: "flex",
    justifyContent: "space-between",
    gap: 12,
    color: "#ccc",
    fontSize: 14,
    fontWeight: 700,
  },
};
